_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.10.16
            "5": 0.18.3
            "8":
                - 5
            "12": 0.18.3
            "13": darwin-arm64
